### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by pault-oc** [storckmi/odmsummary#1]
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.
## Missing:

1) de.unimuenster.imi:org.cdisc.odm.v132:jar:1.1.0

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=de.unimuenster.imi -DartifactId=org.cdisc.odm.v132 -Dversion=1.1.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=de.unimuenster.imi -DartifactId=org.cdisc.odm.v132 -Dversion=1.1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
        1) de.imi:ODMToolbox:war:1.0
        2) de.unimuenster.imi:org.cdisc.odm.v132:jar:1.1.0

---

1 required artifact is missing.

for artifact:
  de.imi:ODMToolbox:war:1.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  imi-internal-repository (https://codecheck.uni-muenster.de/artifactory/list/imi-internal-repository/),
  eclipselink (http://download.eclipse.org/rt/eclipselink/maven.repo/),
  google-maven-snapshot-repository (https://oss.sonatype.org/content/repositories/google-snapshots/)

**Comment by storckmi** [comment]
This dependency was unnecessary anyway, so it was deleted.

**Comment by pault-oc** [comment]
Thanks!
